message: hiiiihello
spring: 
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    password: ~
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: root
  jpa: 
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
