spring:
   profiles: dev
   datasource:
      url: jdbc:mysql://localhost/devdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 
message: I AM DEV
   jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
---
spring:
   profiles: test
   datasource:
      url: jdbc:mysql://localhost/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 
message: I AM TSET
   jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
---
spring:
   profiles: prod
   datasource:
      url: jdbc:mysql://localhost/proddb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 
message: I AM PROD
   jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
